### ISSUE TITLE
why are the entries for database access in the config file?

### ISSUE THREAD

**Issue by propertunist** [abeMedia/shareCount#15]
as far as i am seeing, the database credentials supplied in the config file are never used anywhere in the code - did i miss something?

**Comment by abeMedia** [comment]
It is because I was going to integrate stats using a database back-end at the time but then ended up rewriting the whole API in Golang for performance reasons. So to answer your question: no, they serve no purpose.

Maybe I will still integrate it if the demand is there but since this script is no longer used in our business it's currently not very likely.

**Comment by propertunist** [comment]
oh ok, no problem; i was just wanting to understand the code and that caused me to scratch my head a while. ;)
