### ISSUE TITLE
Twitter share count don't show

### ISSUE THREAD

**Issue by enjoyiacm** [abeMedia/shareCount#16]
Hey.

At 20 Nov 2015 Twitter no longer support API 1.0. This is new way to get it: https://dev.twitter.com/rest/reference/get/search/tweets

Fix it, please.

**Comment by abeMedia** [comment]
Hi, sadly it's not quite that simple... You can read more about the problems in [this thread](https://twittercommunity.com/t/clarification-about-share-counts-for-the-new-tweet-button/52868/24). It appears the only solution is the streaming API, counting the tweets in a local DB, as they come in in real-time. Since this script isn't used in our business anymore it's unlikely something like that will be integrated. Will need to do a little more research into the subject though and if there is a simple solution out there I might well do it.

**Comment by pagelab** [comment]
Looks like someone released an open tool to do this: http://opensharecount.com/

Didn't test it yet, so can't confirm if it's legit. But it needs access to your twitter account.

**Comment by enjoyiacm** [comment]
This way is too ugly but works... if you need share count for only ONE domain..

**Comment by propertunist** [comment]
providing profile access for twitter to a 3rd party is far from optimal!

**Comment by abeMedia** [comment]
It's far from ideal indeed. Also, it's not rocket science how they do it. If someone would be interested in having a bash I'm happy to help them but right now I don't have the time to do it myself.
